### ISSUE TITLE
👴🐘😀

### ISSUE THREAD

**Issue by JolyneCujoh-sf** [sagerlikesspring/HealthCode-sim#4]
When Communist Party Killed me, I'll laugh, 'cause they sent me to communist hell, experience hungry, struggle session and mind rape.

**Comment by Old-8-canteen** [comment]
> 
> 
> When Communist Party Killed me, I'll laugh, 'cause they sent me to communist hell, experience hungry, struggle session and mind rape.

🤡1🐏💉 🥺
